version: '3.7'

networks:
  test_network:
    name: test_network

services:
  zookeeper:
      image: confluentinc/cp-zookeeper:5.5.0
      container_name: zookeeper
      ports:
        - '2181:2181'
      networks:
        - test_network
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-kafka:5.5.0
    container_name: kafka-broker
    networks:
      - test_network
    ports:
      - '19092:19092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongodb_container:
    image: mongo:latest
    networks:
      - test_network
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
